import { type NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {


  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="text-center text-4xl font-bold">Welcome to T3 App!</h1>
      </main>
    </>
  );
};

export default Home;
